### ISSUE TITLE
Simplify access to Tinytest code

### ISSUE THREAD

**Issue by mitar** [peerlibrary/meteor-classy-test#9]
Now that this [pull request](https://github.com/meteor/meteor/pull/3541) was merged in we can access symbols directly and do not need to pull Tinytest code directly in.

**Comment by gregorynicholas** [comment]
was it merged ?

**Comment by mitar** [comment]
Yes: https://github.com/meteor/meteor/commit/9e399547e5bac8a604a9eb1bd612015cabd50fe6

**Comment by gregorynicholas** [comment]
awesome.. is that in the 1.3x track?

**Comment by mitar** [comment]
It seems so. In the [commit](https://github.com/meteor/meteor/commit/9e399547e5bac8a604a9eb1bd612015cabd50fe6) you can see in which Meteor branches it is.

**Comment by mitar** [comment]
It is in `release/METEOR@1.3` for example.

**Comment by mitar** [comment]
Done.
